/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RiskDisclosureRouteImport } from './routes/risk-disclosure'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEaLicensesRouteImport } from './routes/_authenticated/ea-licenses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicCheckRouteImport } from './routes/api/public/check'
import { Route as AuthenticatedCheckoutPlanRouteImport } from './routes/_authenticated/checkout.$plan'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicEaLicenseCheckRouteImport } from './routes/api/public/ea-license/check'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclosureRoute = RiskDisclosureRouteImport.update({
  id: '/risk-disclosure',
  path: '/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEaLicensesRoute = AuthenticatedEaLicensesRouteImport.update({
  id: '/ea-licenses',
  path: '/ea-licenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCheckRoute = ApiPublicCheckRouteImport.update({
  id: '/api/public/check',
  path: '/api/public/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutPlanRoute =
  AuthenticatedCheckoutPlanRouteImport.update({
    id: '/checkout/$plan',
    path: '/checkout/$plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEaLicenseCheckRoute = ApiPublicEaLicenseCheckRouteImport.update({
  id: '/api/public/ea-license/check',
  path: '/api/public/ea-license/check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ea-licenses': typeof AuthenticatedEaLicensesRoute
  '/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/ea-license/check': typeof ApiPublicEaLicenseCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ea-licenses': typeof AuthenticatedEaLicensesRoute
  '/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/ea-license/check': typeof ApiPublicEaLicenseCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/ea-licenses': typeof AuthenticatedEaLicensesRoute
  '/_authenticated/checkout/$plan': typeof AuthenticatedCheckoutPlanRoute
  '/api/public/check': typeof ApiPublicCheckRoute
  '/api/public/ea-license/check': typeof ApiPublicEaLicenseCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/privacy-policy'
    | '/refund-policy'
    | '/risk-disclosure'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/ea-licenses'
    | '/checkout/$plan'
    | '/api/public/check'
    | '/api/public/ea-license/check'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/privacy-policy'
    | '/refund-policy'
    | '/risk-disclosure'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/ea-licenses'
    | '/checkout/$plan'
    | '/api/public/check'
    | '/api/public/ea-license/check'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/auth'
    | '/contact'
    | '/privacy-policy'
    | '/refund-policy'
    | '/risk-disclosure'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/ea-licenses'
    | '/_authenticated/checkout/$plan'
    | '/api/public/check'
    | '/api/public/ea-license/check'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RiskDisclosureRoute: typeof RiskDisclosureRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCheckRoute: typeof ApiPublicCheckRoute
  ApiPublicEaLicenseCheckRoute: typeof ApiPublicEaLicenseCheckRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclosure': {
      id: '/risk-disclosure'
      path: '/risk-disclosure'
      fullPath: '/risk-disclosure'
      preLoaderRoute: typeof RiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ea-licenses': {
      id: '/_authenticated/ea-licenses'
      path: '/ea-licenses'
      fullPath: '/ea-licenses'
      preLoaderRoute: typeof AuthenticatedEaLicensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/check': {
      id: '/api/public/check'
      path: '/api/public/check'
      fullPath: '/api/public/check'
      preLoaderRoute: typeof ApiPublicCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout/$plan': {
      id: '/_authenticated/checkout/$plan'
      path: '/checkout/$plan'
      fullPath: '/checkout/$plan'
      preLoaderRoute: typeof AuthenticatedCheckoutPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ea-license/check': {
      id: '/api/public/ea-license/check'
      path: '/api/public/ea-license/check'
      fullPath: '/api/public/ea-license/check'
      preLoaderRoute: typeof ApiPublicEaLicenseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEaLicensesRoute: typeof AuthenticatedEaLicensesRoute
  AuthenticatedCheckoutPlanRoute: typeof AuthenticatedCheckoutPlanRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEaLicensesRoute: AuthenticatedEaLicensesRoute,
  AuthenticatedCheckoutPlanRoute: AuthenticatedCheckoutPlanRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RiskDisclosureRoute: RiskDisclosureRoute,
  TermsRoute: TermsRoute,
  ApiPublicCheckRoute: ApiPublicCheckRoute,
  ApiPublicEaLicenseCheckRoute: ApiPublicEaLicenseCheckRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
